# Generated by Django 5.0.2 on 2024-02-10 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('departure_Time', models.DateField()),
                ('reach_Time', models.DateField()),
                ('fare', models.IntegerField()),
                ('end', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end', to='base.location')),
                ('start', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start', to='base.location')),
            ],
        ),
    ]
