# Generated by Django 5.0.2 on 2024-02-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_location_alter_user_email_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='departure_Time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='reach_Time',
            field=models.TimeField(),
        ),
    ]
