# Generated by Django 5.0.2 on 2024-02-10 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.IntegerField()),
                ('fare', models.IntegerField()),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endt', to='base.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startt', to='base.location')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.train')),
            ],
        ),
    ]
