# Generated by Django 5.0.2 on 2024-02-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_train_numb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='numb',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
